# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_port(object):
    def setupUi(self, port):
        port.setObjectName("port")
        port.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=port)
        self.centralwidget.setObjectName("centralwidget")
        self.Username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(270, 170, 201, 31))
        self.Username.setObjectName("Username")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 170, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setGeometry(QtCore.QRect(270, 230, 201, 31))
        self.password.setObjectName("password")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 230, 71, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.login.setGeometry(QtCore.QRect(300, 360, 131, 28))
        self.login.setObjectName("login")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 280, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Port = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Port.setGeometry(QtCore.QRect(270, 270, 191, 31))
        self.Port.setObjectName("Port")
        port.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=port)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        port.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=port)
        self.statusbar.setObjectName("statusbar")
        port.setStatusBar(self.statusbar)

        self.retranslateUi(port)
        QtCore.QMetaObject.connectSlotsByName(port)

    def retranslateUi(self, port):
        _translate = QtCore.QCoreApplication.translate
        port.setWindowTitle(_translate("port", "MainWindow"))
        self.Username.setText(_translate("port", "Enter Username"))
        self.label.setText(_translate("port", "   Username:"))
        self.password.setText(_translate("port", "Enter Password"))
        self.label_2.setText(_translate("port", "Password:"))
        self.login.setText(_translate("port", "Login"))
        self.label_3.setText(_translate("port", "    Port:"))
        self.Port.setText(_translate("port", "Enter Port"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    port = QtWidgets.QMainWindow()
    ui = Ui_port()
    ui.setupUi(port)
    port.show()
    sys.exit(app.exec())
