# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_online = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_online.setFont(font)
        self.groupBox_online.setTitle("")
        self.groupBox_online.setObjectName("groupBox_online")
        self.List_online = QtWidgets.QListWidget(parent=self.groupBox_online)
        self.List_online.setGeometry(QtCore.QRect(0, 80, 141, 241))
        self.List_online.setObjectName("List_online")
        self.online_text = QtWidgets.QLabel(parent=self.groupBox_online)
        self.online_text.setGeometry(QtCore.QRect(10, 50, 81, 31))
        self.online_text.setObjectName("online_text")
        self.chat = QtWidgets.QGroupBox(parent=self.groupBox_online)
        self.chat.setGeometry(QtCore.QRect(430, 70, 271, 261))
        self.chat.setObjectName("chat")
        self.Chat_1 = QtWidgets.QTextBrowser(parent=self.chat)
        self.Chat_1.setGeometry(QtCore.QRect(10, 30, 256, 192))
        self.Chat_1.setObjectName("Chat_1")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_online)
        self.label_2.setGeometry(QtCore.QRect(60, 380, 131, 16))
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox_online)
        self.lineEdit.setGeometry(QtCore.QRect(150, 370, 271, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.send_button = QtWidgets.QPushButton(parent=self.groupBox_online)
        self.send_button.setGeometry(QtCore.QRect(450, 370, 93, 28))
        self.send_button.setObjectName("send_button")
        self.horizontalLayout.addWidget(self.groupBox_online)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.online_text.setText(_translate("MainWindow", "ONLINE"))
        self.chat.setTitle(_translate("MainWindow", "Chat"))
        self.label_2.setText(_translate("MainWindow", "Message:"))
        self.lineEdit.setText(_translate("MainWindow", "Nhập tin nhắn ở đây"))
        self.send_button.setText(_translate("MainWindow", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
